openapi: 3.0.0
info:
  version: "v1-oas3"
  title: Asgardeo - Password Recovery API
  description: |
    This is the RESTful API for password recovery initiated by the user.
    <br> To access this API in Asgardeo, you need to first [get an access token](https://wso2.com/asgardeo/docs/apis/authentication/#get-an-access-token) from your organization using the following scopes.

    <b>Scopes required:<br> </b>
    - ```internal_identity_mgt_view```
    - ```internal_identity_mgt_update```
    - ```internal_identity_mgt_create```
    - ```internal_identity_mgt_delete```

security:
  - OAuth2: []
servers:
  - url: 'https://api.asgardeo.io/t/{organization-name}/api/users/v2'
paths:
  /recovery/password/init:
    post:
      tags:
        - Password Recovery
      summary: |
        Initiate password recovery
      operationId: initiatePasswordRecovery
      description: |
        This API is used to initiate the password recovery flow. The API will return recovery information for password recovery.
      responses:
        '200':
          description: |
            The user is successfully identified for the given claims and returning available notification channels for the user.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountRecoveryType'
              examples:
                response:
                  value:
                    - mode: recoverWithNotifications
                      flowConfirmationCode: 1234-1234-1234-1234
                      channelInfo:
                        recoveryCode: 1234-55678-5668-2345
                        channels:
                          - id: 1
                            type: EMAIL
                            value: wso2***********.com
                            preferred: false
                          - id: 2
                            type: SMS
                            value: '**********123'
                            preferred: true
                      links:
                        - rel: next
                          href: /api/users/v2/recovery/password/recovery
                          type: POST
        '400':
          description: Bad Request. The request cannot be processed by the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10001
                    message: bad_request
                    description: Bad request.
                    traceId: 23456fghj678vb78
        '404':
          description: >-
            No user found for the given set of claims or no recovery channels
            are availabe for the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10002
                    message: Not found
                    description: No user found.
                    traceId: 23456fghj678vb78
        '409':
          description: Multiple users were found for the given claims.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10008
                    message: Conflict
                    description: Multiple users were found for given claims.
                    traceId: 23456fghj678vb78
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-15001
                    message: Internal Error
                    description: Internal Error.
                    traceId: 23456fghj678vb78
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v2/recovery/password/init' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "claims": [
              {
                "uri": "http://wso2.org/claims/givenname",
                "value": "user1"
              }
            ],
            "properties": [
              {
                "key": "key",
                "value": "value"
              }
            ]
            }'                   
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitRequest'
        description: |
          Request to initiate password recovery process. The request should contain the claims to identify the user. User claims are `REQUIRED`.
        required: true
  /recovery/password/recover:
    post:
      tags:
        - Password Recovery
      summary: |
        Get recovery information
      operationId: recoverPassword
      description: |
        This API is used to send recovery information to the user who matches the recovery code via the channel specified by the channel ID.
        The API will return the recovery flow confirmation code.
      responses:
        '202':
          description: |
            - Password recovery initiated via internal channels. API will send a `confirmationCode`/`otp` to the channel specified by the user.
            - Use the confirmation code/OTP with "password recovery confirm API" to confirm the password recovery.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordRecoveryInternalNotifyResponse'
              examples:
                response:
                  value:
                    code: PWR-02002
                    message: Password recovery information sent via user preferred notification channel.
                    flowConfirmationCode: 1234-1234-1234-1234
                    notificationChannel: EMAIL
                    resendCode: 12345-45678-6789098-8765
                    links:
                      - rel: next
                        href: api/users/v2/recovery/password/confirm
                        type: POST
                      - rel: resend
                        href: api/users/v2/recovery/password/resend
                        type: POST
        '400':
          description: Bad Request. Request cannot be processed by the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: bad_request
                    description: Bad request
                    traceId: 23456fghj678vb78
        '403':
          description: Password recovery is not enabled.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10004
                    message: Forbidden
                    description: Password recovery is not enabled.
                    traceId: 23456fghj678vb78
        '404':
          description: Recovery code is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: not_found
                    description: Recovery code not found.
                    traceId: 23456fghj678vb78
        '406':
          description: |
            - The recovery code given in the request is not valid or expired.
            - Channel ID is not valid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10003
                    message: not acceptable
                    description: 'invalid error code: 1234-2345-12345-123456'
                    traceId: 23456fghj678vb78
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-15001
                    message: Internal Error
                    description: Internal Error
                    traceId: 23456fghj678vb78
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v2/recovery/password/recover' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "recoveryCode": "1234-5678-2455-3433",
            "channelId": "1",
            "properties": [
              {
                "key": "key",
                "value": "value"
              }
            ]
            }'                   
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecoveryRequest'
        description: |
          - Request to receive recovery notifications.
          - The `recoveryCode` and `channelId` are required fields.
          - Note that the `channelId` should always be a value larger than `0`.
        required: true
  /recovery/password/resend:
    post:
      tags:
        - Password Recovery
      summary: |
        Resend password recovery confirmation details
      operationId: resendConfirmation
      description: |
        - This API is used to resend a `confirmation code`/`OTP` to the user via a user-preferred channel defined at password recovery.
        - The API will return the next API calls.
      responses:
        '202':
          description: |
            - This API will send a `confirmationCode`/`otp` to the channel specified by the user.
            - Use the confirmation code/OTP with "password recovery confirm API" to confirm the password recovery.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResendConfirmationCodeInternalResponse'
              examples:
                response:
                  value:
                    code: PWR-02002
                    message: successful_request
                    flowConfirmationCode: 1234-1234-1234-1234
                    notificationChannel: EMAIL
                    resendCode: 1234-12345-234-123456
                    links:
                      - rel: next
                        href: api/user/v2/recovery/password/recover
                        type: POST
                      - rel: resend
                        href: api/users/v2/recovery/password/resend
                        type: POST
        '400':
          description: Bad Request. Request cannot be processed by the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10001
                    message: bad_request
                    description: Bad request.
                    traceId: 23456fghj678vb78
        '404':
          description: Resend code is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10001
                    message: not_found
                    description: Recovery code not found.
                    traceId: 23456fghj678vb78
        '406':
          description: The Resend code given in the request is not valid or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-10003
                    message: not acceptable
                    description: 'invalid error code: 1234-2345-12345-123456'
                    traceId: 23456fghj678vb78
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: UAR-15001
                    message: Internal Error
                    description: Internal Error
                    traceId: 23456fghj678vb78
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v2/recovery/password/resend' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "resendCode": "1234-2ws34-1234",
            "properties": [
              {
                "key": "key",
                "value": "value"
              }
            ]
            }'                  
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResendConfirmationRequest'
        description: |
          Request to resend the `confirmationCode`/`otp` to the user via a user preferred channel.
        required: true
  /recovery/password/confirm:
    post:
      tags:
        - Password Recovery
      summary: |
        Confirm password recovery
      operationId: confirmRecovery
      description: |
        - This API is used to validate the `confirmationCode`/`otp` given at password recovery.
        - Use the returned `reset code` with the "password reset API" to reset the password.
        - The API will return the `reset code` and the next API call.
      responses:
        '200':
          description: |
            - Password reset confirmed.
            - Use the returned `resetCode` with the "password reset API" to reset the password.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetCodeResponse'
              examples:
                response:
                  value:
                    resetCode: 2806aed9-fe7c-4b47-a91f-0aa897fac9a2
                    links:
                      - rel: next
                        href: |
                          /t/{organization-name}/api/users/v2/recovery/password/reset
                        type: POST
        '400':
          description: Bad Request. Request cannot be processed by the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: bad_request
                    description: Bad request.
                    traceId: 23456fghj678vb78
        '404':
          description: Confirmation code is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: not_found
                    description: Recovery code not found.
                    traceId: 23456fghj678vb78
        '406':
          description: |
            The confirmation code given in the request is not valid or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: not acceptable
                    description: 'invalid error code: 1234-2345-12345-123456'
                    traceId: 23456fghj678vb78
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-15001
                    message: Internal Error
                    description: Internal Error
                    traceId: 23456fghj678vb78
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v2/recovery/password/confirm' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "confirmationCode": "1234-2ws34-12345",
            "otp": "wi8Ivm",
            "properties": [
              {
                "key": "key",
                "value": "value"
              }
            ]
            }'                    
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmRequest'
        description: |
          - Request to confirm the password recovery.
          - `confirmationCode` is `REQUIRED`.
          - `otp` is required only for OTP based password recovery. The `flowConfirmationCode` returned from the password recovery request should be set as the `confirmationCode` for OTP-based recovery.
        required: true
  /recovery/password/reset:
    post:
      tags:
        - Password Recovery
      summary: |
        Reset password
      operationId: resetPassword
      description: >
        This API is used to reset the password of the user who matches the flowConfirmationCode given by the recover API and the resetCode given by the confirmation API.
      responses:
        '200':
          description: Successful password reset.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PasswordResetResponse'
              examples:
                response:
                  value:
                    code: PWR-02005
                    message: Successful password reset
        '400':
          description: Bad Request. Request cannot be processed by the server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: bad_request
                    description: Bad request.
                    traceId: 23456fghj678vb78
        '404':
          description: Reset code is not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: not_found
                    description: Recovery code not found.
                    traceId: 23456fghj678vb78
        '406':
          description: The reset code given in the request is not valid or expired.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: not acceptable
                    description: 'invalid error code: 1234-2345-12345-123456'
                    traceId: 23456fghj678vb78
        '412':
          description: Password policy violation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetryErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-10001
                    message: bad_request
                    description: Password policy violation.
                    traceId: 23456fghj678vb78
                    resetCode: 1234-12345-sdf-34567567
                    links: [
                      {
                        "rel": "next",
                        "href": "/t/{organization-name}/api/users/v2/recovery/password/reset",
                        "type": "POST"
                      }
                    ]
        '500':
          description: Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                response:
                  value:
                    code: PWR-15001
                    message: Internal Error
                    description: Internal Error
                    traceId: 23456fghj678vb78
      x-codeSamples:
        - lang: Curl
          source: |
            curl -X 'POST' \
            'https://api.asgardeo.io/t/{organization-name}/api/users/v2/recovery/password/reset' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Bearer {bearer_token}' \
            -d '{
            "resetCode": "string",
            "flowConfirmationCode": "string",
            "password": "string",
            "properties": [
              {
                "key": "key",
                "value": "value"
              }
            ]
            }'                   
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetRequest'
        description: |
          - Request to reset the password.
          - `resetCode`, `flowConfirmationCode` and `password` are required.
        required: true
components:
  schemas:
    InitRequest:
      type: object
      description: Request to initiate an account recovery
      properties:
        claims:
          type: array
          description: The user claims to identify the user as `UserClaim` objects.
          items:
            $ref: '#/components/schemas/UserClaim'
        properties:
          type: array
          description: (OPTIONAL) Additional META properties
          items:
            $ref: '#/components/schemas/Property'
      required:
        - claims
    RecoveryRequest:
      type: object
      description: |
        Request to start the password recovery for the user who matches with the recovery code via the given `channelId`.
      properties:
        recoveryCode:
          type: string
          description: Recovery code for the user.
          example: 1234-5678-2455-3433
        channelId:
          type: string
          description: |
            The identifier of the notification channel that the user prefers to get recovery notifications.
          example: '1'
        properties:
          type: array
          description: (OPTIONAL) Additional META properties.
          items:
            $ref: '#/components/schemas/Property'
      required:
        - recoveryCode
        - channelId
    ResendConfirmationRequest:
      type: object
      description: Request to resend the confirmation code in password recovery.
      properties:
        resendCode:
          type: string
          description: Resend code returned by the password recovery API.
          example: 1234-2ws34-1234
        properties:
          type: array
          description: (OPTIONAL) Additional META properties.
          items:
            $ref: '#/components/schemas/Property'
    ConfirmRequest:
      type: object
      description: Request to confirm password recovery.
      required:
        - confirmationCode
      properties:
        confirmationCode:
          type: string
          description: Confirmation code of the recovery flow.
          example: 1234-2ws34-12345
        otp:
          type: string
          description: OTP sent to the user
          example: wi8Ivm
        properties:
          type: array
          description: (OPTIONAL) Additional META properties.
          items:
            $ref: '#/components/schemas/Property'
    ResetRequest:
      type: object
      description: Object to reset the password of a user.
      required:
        - resetCode
        - flowConfirmationCode
        - password
      properties:
        resetCode:
          type: string
          description: resetCode given by the confirm API.
        flowConfirmationCode:
          type: string
          description: Confirmation code of the recovery flow.
        password:
          type: string
          description: New password given by the user.
        properties:
          type: array
          description: (OPTIONAL) Additional META properties.
          items:
            $ref: '#/components/schemas/Property'
    PasswordRecoveryInternalNotifyResponse:
      type: object
      properties:
        code:
          type: string
          description: Success status code.
          example: PWR-02002
        message:
          type: string
          description: Success status message.
          example: successful_request
        flowConfirmationCode:
          type: string
          description: Recovery flow confirmation code.
          example: 1234-1234-1234-1234
        notificationChannel:
          type: string
          description: Channel that is used to send recovery information.
          example: EMAIL
        resendCode:
          type: string
          description: |
            Code to resend the confirmation code to the user via the user-selected channel.
          example: 1234-123456-12345-12345
        links:
          type: array
          description: Contains next available API calls.
          items:
            $ref: '#/components/schemas/APICall'
    ResetCodeResponse:
      properties:
        resetCode:
          type: string
          description: Password reset code to reset the password.
          example: 1234-55678-5668-2345
        links:
          type: array
          description: Contains next available API calls.
          items:
            $ref: '#/components/schemas/APICall'
    PasswordResetResponse:
      type: object
      description: API response for a successful password reset.
      properties:
        code:
          type: string
          description: Operation code
          example: PWR-02001
        message:
          type: string
          description: Message regarding the operation.
          example: successful_request
    ResendConfirmationCodeInternalResponse:
      type: object
      description: The object encapsulates the details regarding the resend confirmation code.
      properties:
        code:
          type: string
          description: Success status code.
          example: PWR-02002
        message:
          type: string
          description: Success status message.
          example: successful_request
        flowConfirmationCode:
          type: string
          description: Recovery flow confirmation code.
          example: 1234-1234-1234-1234
        notificationChannel:
          type: string
          description: Channel that is used to send recovery information.
          example: EMAIL
        resendCode:
          type: string
          description: The code to resend the confirmation code.
          example: 1234-12345-234-123456
        links:
          type: array
          description: Contains next available API calls.
          items:
            $ref: '#/components/schemas/APICall'
    RetryErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code corresponding to the error.
          example: PWR-10004
        message:
          type: string
          description: Error message
          example: Retry
        description:
          type: string
          description: Error description
          example: Password policy violation
        traceId:
          type: string
          description: Some correlation for error instance.
          example: 2345dfgh678h789bhjk
        resetCode:
          type: string
          description: Password reset code used in the request.
          example: 1234-34567-3456-2345678
        links:
          type: array
          description: Contains next available API calls.
          items:
            $ref: '#/components/schemas/APICall'
    ErrorResponse:
      type: object
      properties:
        code:
          type: string
          description: Error code corresponding to the error.
          example: UAR-10001
        message:
          type: string
          description: Error message
          example: invalid_request
        description:
          type: string
          description: Description of the error.
          example: Invalid claim uri
        traceId:
          type: string
          description: Some correlation for error instance.
          example: 2345dfgh678h789bhjk
    AccountRecoveryType:
      type: object
      description: Object that encapsulates details of the account recovery channel.
      properties:
        mode:
          type: string
          example: recoverWithNotifications
        flowConfirmationCode:
          type: string
          example: 1234-1234-1234-1234
        channelInfo:
          $ref: '#/components/schemas/RecoveryChannelInformation'
        links:
          type: array
          description: Contains next available API calls.
          items:
            $ref: '#/components/schemas/APICall'
    RecoveryChannelInformation:
      description: Response with the recovery ID and the available recovery channels.
      properties:
        recoveryCode:
          type: string
          description: Code to recover the user account.
          example: 1234-55678-5668-2345
        channels:
          type: array
          description: Lists the available recovery channels for the user.
          items:
            $ref: '#/components/schemas/RecoveryChannel'
    RecoveryChannel:
      type: object
      description: Object with notification channel attributes.
      properties:
        id:
          type: string
          description: Identifier given to the channel.
          example: '1'
        type:
          type: string
          description: Type of the channel.
          example: EMAIL
        value:
          type: string
          description: Masked channel value.
          example: wso2***********.com
        preferred:
          type: boolean
          description: Specifies whether the channel is a user-preferred channel.
          example: true
    UserClaim:
      type: object
      description: Object that holds a user claim and the corresponding value.
      properties:
        uri:
          type: string
          description: Claim uri
          example: 'http://wso2.org/claims/givenname'
        value:
          type: string
          description: Value for the claim.
          example: user1
    Property:
      type: object
      description: Object that holds a property as a key, value pair.
      properties:
        key:
          type: string
          description: Unique identifier as the key of the property.
          example: key
        value:
          type: string
          description: Value of the property.
          example: value
    APICall:
      type: object
      description: Object that holds the next API call details.
      properties:
        rel:
          type: string
          description: Next API call.
          example: next
        href:
          type: string
          description: Next API URL.
          example: /api/users/recovery/v2/
        type:
          type: string
          description: HTTP method type.
          example: POST
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://api.asgardeo.io/t/{org-name}/oauth2/token'
          scopes:
            internal_identity_mgt_view: Grants read access
            internal_identity_mgt_create: Grants write access
            internal_identity_mgt_delete: Grants permission to delete records
            internal_identity_mgt_update: Grants permission to update existing records